export const countryCodes = [
  { name: "afghanistan", code: "af" },
  { name: "albania", code: "al" },
  { name: "algeria", code: "dz" },
  { name: "american_samoa", code: "as" },
  { name: "andorra", code: "ad" },
  { name: "angola", code: "ao" },
  { name: "anguilla", code: "ai" },
  { name: "antarctica", code: "aq" },
  { name: "antigua_and_barbuda", code: "ag" },
  { name: "argentina", code: "ar" },
  { name: "armenia", code: "am" },
  { name: "aruba", code: "aw" },
  { name: "australia", code: "au" },
  { name: "austria", code: "at" },
  { name: "azerbaijan", code: "az" },
  { name: "bahamas", code: "bs" },
  { name: "bahrain", code: "bh" },
  { name: "bangladesh", code: "bd" },
  { name: "barbados", code: "bb" },
  { name: "belarus", code: "by" },
  { name: "belgium", code: "be" },
  { name: "belize", code: "bz" },
  { name: "benin", code: "bj" },
  { name: "bermuda", code: "bm" },
  { name: "bhutan", code: "bt" },
  { name: "bolivia", code: "bo" },
  { name: "bonaire", code: "bq" },
  { name: "bosnia_and_herzegovina", code: "ba" },
  { name: "botswana", code: "bw" },
  { name: "bouvet_island", code: "bv" },
  { name: "brazil", code: "br" },
  { name: "british_indian_ocean_territory", code: "io" },
  {
    name: "brunei_darussalam",
    code: "bn",
  },
  { name: "bulgaria", code: "bg" },
  { name: "burkina_faso", code: "bf" },
  { name: "burundi", code: "bi" },
  { name: "cabo_verde", code: "cv" },
  { name: "cambodia", code: "kh" },
  { name: "cameroon", code: "cm" },
  { name: "canada", code: "ca" },
  { name: "cayman_islands", code: "ky" },
  { name: "central_african_republic", code: "cf" },
  { name: "chad", code: "td" },
  { name: "chile", code: "cl" },
  { name: "china", code: "cn" },
  { name: "christmas_island", code: "cx" },
  { name: "cocos_islands", code: "cc" },
  { name: "colombia", code: "co" },
  { name: "comoros", code: "km" },
  { name: "congo", code: "cg" },
  { name: "cook_islands", code: "ck" },
  { name: "costa_rica", code: "cr" },
  { name: "croatia", code: "hr" },
  { name: "cuba", code: "cu" },
  { name: "curaçao", code: "cw" },
  { name: "cyprus", code: "cy" },
  { name: "czechia", code: "cz" },
  { name: "côte_d'ivoire", code: "ci" },
  { name: "denmark", code: "dk" },
  { name: "djibouti", code: "dj" },
  { name: "dominica", code: "dm" },
  { name: "dominican_republic", code: "do" },
  { name: "ecuador", code: "ec" },
  { name: "egypt", code: "eg" },
  { name: "el_salvador", code: "sv" },
  { name: "equatorial_guinea", code: "gq" },
  { name: "eritrea", code: "er" },
  { name: "estonia", code: "ee" },
  { name: "eswatini", code: "sz" },
  { name: "england", code: "gb" },
  { name: "ethiopia", code: "et" },
  { name: "ethiopia", code: "et" },
  { name: "falkland_islands", code: "fk" },
  {
    name: "faroe_islands",
    code: "fo",
  },
  { name: "fiji", code: "fj" },
  { name: "finland", code: "fi" },
  { name: "france", code: "fr" },
  { name: "french_guiana", code: "gf" },
  {
    name: "french_polynesia",
    code: "pf",
  },
  { name: "french_southern_territories", code: "tf" },
  { name: "gabon", code: "ga" },
  { name: "gambia", code: "gm" },
  { name: "georgia", code: "ge" },
  { name: "germany", code: "de" },
  { name: "ghana", code: "gh" },
  { name: "gibraltar", code: "gi" },
  { name: "greece", code: "gr" },
  { name: "greenland", code: "gl" },
  { name: "grenada", code: "gd" },
  { name: "guadeloupe", code: "gp" },
  { name: "guam", code: "gu" },
  { name: "guatemala", code: "gt" },
  { name: "guernsey", code: "gg" },
  { name: "guinea", code: "gn" },
  { name: "guinea-bissau", code: "gw" },
  { name: "guyana", code: "gy" },
  { name: "haiti", code: "ht" },
  { name: "heard_island_and_mcdonald_islands", code: "hm" },
  { name: "holy_see", code: "va" },
  { name: "colombia", code: "co" },
  { name: "comoros", code: "km" },
  { name: "congo", code: "cg" },
  { name: "cook_islands", code: "ck" },
  { name: "costa_rica", code: "cr" },
  { name: "croatia", code: "hr" },
  { name: "cuba", code: "cu" },
  { name: "curaçao", code: "cw" },
  { name: "cyprus", code: "cy" },
  { name: "czechia", code: "cz" },
  {
    name: "côte_d'ivoire",
    code: "ci",
  },
  { name: "denmark", code: "dk" },
  { name: "djibouti", code: "dj" },
  { name: "dominica", code: "dm" },
  {
    name: "dominican_republic",
    code: "do",
  },
  { name: "ecuador", code: "ec" },
  { name: "egypt", code: "eg" },
  { name: "el_salvador", code: "sv" },
  {
    name: "equatorial_guinea",
    code: "gq",
  },
  { name: "eritrea", code: "er" },
  { name: "estonia", code: "ee" },
  { name: "eswatini", code: "sz" },
  { name: "ethiopia", code: "et" },
  { name: "falkland_islands", code: "fk" },
  {
    name: "faroe_islands",
    code: "fo",
  },
  { name: "fiji", code: "fj" },
  { name: "finland", code: "fi" },
  { name: "france", code: "fr" },
  { name: "french_guiana", code: "gf" },
  {
    name: "french_polynesia",
    code: "pf",
  },
  {
    name: "french_southern_territories",
    code: "tf",
  },
  { name: "gabon", code: "ga" },
  { name: "gambia", code: "gm" },
  { name: "georgia", code: "ge" },
  { name: "germany", code: "de" },
  { name: "ghana", code: "gh" },
  { name: "gibraltar", code: "gi" },
  { name: "greece", code: "gr" },
  { name: "greenland", code: "gl" },
  { name: "grenada", code: "gd" },
  { name: "guadeloupe", code: "gp" },
  { name: "guam", code: "gu" },
  { name: "guatemala", code: "gt" },
  { name: "guernsey", code: "gg" },
  { name: "guinea", code: "gn" },
  {
    name: "guinea-bissau",
    code: "gw",
  },
  { name: "guyana", code: "gy" },
  { name: "haiti", code: "ht" },
  {
    name: "heard_island_and_mcdonald_islands",
    code: "hm",
  },
  { name: "holy_see", code: "va" },
  { name: "honduras", code: "hn" },
  { name: "hong_kong", code: "hk" },
  { name: "hungary", code: "hu" },
  { name: "iceland", code: "is" },
  { name: "india", code: "in" },
  { name: "indonesia", code: "id" },
  { name: "iran", code: "ir" },
  { name: "iraq", code: "iq" },
  { name: "ireland", code: "ie" },
  { name: "isle_of_man", code: "im" },
  { name: "israel", code: "il" },
  { name: "italy", code: "it" },
  { name: "jamaica", code: "jm" },
  { name: "japan", code: "jp" },
  { name: "jersey", code: "je" },
  { name: "jordan", code: "jo" },
  { name: "kazakhstan", code: "kz" },
  { name: "kenya", code: "ke" },
  { name: "kiribati", code: "ki" },
  { name: "korea", code: "kr" },
  { name: "kuwait", code: "kw" },
  { name: "kyrgyzstan", code: "kg" },
  { name: "lao_people's_democratic_republic", code: "la" },
  { name: "latvia", code: "lv" },
  { name: "lebanon", code: "lb" },
  { name: "lesotho", code: "ls" },
  { name: "liberia", code: "lr" },
  { name: "libya", code: "ly" },
  { name: "liechtenstein", code: "li" },
  { name: "lithuania", code: "lt" },
  { name: "luxembourg", code: "lu" },
  { name: "macao", code: "mo" },
  { name: "madagascar", code: "mg" },
  { name: "malawi", code: "mw" },
  { name: "malaysia", code: "my" },
  { name: "maldives", code: "mv" },
  { name: "mali", code: "ml" },
  { name: "malta", code: "mt" },
  { name: "marshall_islands", code: "mh" },
  { name: "martinique", code: "mq" },
  { name: "mauritania", code: "mr" },
  { name: "mauritius", code: "mu" },
  { name: "mayotte", code: "yt" },
  { name: "mexico", code: "mx" },
  { name: "micronesia", code: "fm" },
  { name: "moldova", code: "md" },
  { name: "monaco", code: "mc" },
  { name: "mongolia", code: "mn" },
  { name: "montenegro", code: "me" },
  { name: "montserrat", code: "ms" },
  { name: "morocco", code: "ma" },
  { name: "mozambique", code: "mz" },
  { name: "myanmar", code: "mm" },
  { name: "namibia", code: "na" },
  { name: "nauru", code: "nr" },
  { name: "nepal", code: "np" },
  { name: "netherlands", code: "nl" },
  { name: "new_caledonia", code: "nc" },
  { name: "new_zealand", code: "nz" },
  { name: "nicaragua", code: "ni" },
  { name: "niger", code: "ne" },
  { name: "nigeria", code: "ng" },
  { name: "niue", code: "nu" },
  { name: "norfolk_island", code: "nf" },
  {
    name: "north_macedonia",
    code: "mk",
  },
  { name: "northern_mariana_islands", code: "mp" },
  { name: "norway", code: "no" },
  { name: "oman", code: "om" },
  { name: "pakistan", code: "pk" },
  { name: "palau", code: "pw" },
  { name: "palestine", code: "ps" },
  { name: "panama", code: "pa" },
  { name: "papua_new_guinea", code: "pg" },
  { name: "paraguay", code: "py" },
  { name: "peru", code: "pe" },
  { name: "philippines", code: "ph" },
  { name: "pitcairn", code: "pn" },
  { name: "poland", code: "pl" },
  { name: "portugal", code: "pt" },
  { name: "puerto_rico", code: "pr" },
  { name: "qatar", code: "qa" },
  { name: "romania", code: "ro" },
  { name: "russian_federation", code: "ru" },
  { name: "rwanda", code: "rw" },
  { name: "réunion", code: "re" },
  { name: "saint_barthélemy", code: "bl" },
  { name: "saint_helena", code: "sh" },
  {
    name: "saint_kitts_and_nevis",
    code: "kn",
  },
  { name: "saint_lucia", code: "lc" },
  { name: "saint_martin", code: "mf" },
  { name: "saint_pierre_and_miquelon", code: "pm" },
  {
    name: "saint_vincent_and_the_grenadines",
    code: "vc",
  },
  { name: "samoa", code: "ws" },
  { name: "san_marino", code: "sm" },
  { name: "sao_tome_and_principe", code: "st" },
  { name: "saudi_arabia", code: "sa" },
  { name: "senegal", code: "sn" },
  { name: "serbia", code: "rs" },
  { name: "seychelles", code: "sc" },
  { name: "sierra_leone", code: "sl" },
  { name: "singapore", code: "sg" },
  { name: "sint_maarten", code: "sx" },
  { name: "slovakia", code: "sk" },
  { name: "slovenia", code: "si" },
  { name: "solomon_islands", code: "sb" },
  { name: "somalia", code: "so" },
  { name: "south_africa", code: "za" },
  {
    name: "south_georgia_and_the_south_sandwich_islands",
    code: "gs",
  },
  { name: "south_sudan", code: "ss" },
  { name: "spain", code: "es" },
  { name: "sri_lanka", code: "lk" },
  { name: "sudan", code: "sd" },
  { name: "suriname", code: "sr" },
  { name: "svalbard_and_jan_mayen", code: "sj" },
  { name: "sweden", code: "se" },
  { name: "switzerland", code: "ch" },
  { name: "syrian_arab_republic", code: "sy" },
  { name: "taiwan", code: "tw" },
  { name: "tajikistan", code: "tj" },
  { name: "tanzania", code: "tz" },
  { name: "thailand", code: "th" },
  { name: "timor-leste", code: "tl" },
  { name: "togo", code: "tg" },
  { name: "tokelau", code: "tk" },
  { name: "tonga", code: "to" },
  { name: "trinidad_and_tobago", code: "tt" },
  { name: "tunisia", code: "tn" },
  { name: "turkey", code: "tr" },
  { name: "turkmenistan", code: "tm" },
  { name: "turks_and_caicos_islands", code: "tc" },
  { name: "tuvalu", code: "tv" },
  { name: "uganda", code: "ug" },
  { name: "ukraine", code: "ua" },
  { name: "united_arab_emirates", code: "ae" },
  { name: "united_kingdom", code: "gb" },
  { name: "united_states", code: "us" },
  { name: "united_states_minor_outlying_islands", code: "um" },
  { name: "uruguay", code: "uy" },
  { name: "uzbekistan", code: "uz" },
  { name: "vanuatu", code: "vu" },
  { name: "venezuela", code: "ve" },
  { name: "viet_nam", code: "vn" },
  { name: "virgin_islands", code: "vi" },
  { name: "wallis_and_futuna", code: "wf" },
  { name: "western_sahara", code: "eh" },
  { name: "yemen", code: "ye" },
  { name: "zambia", code: "zm" },
  { name: "zimbabwe", code: "zw" },
  { name: "åland_islands", code: "ax" },
];
